// javascript/vue-app/src/App.vue
<script setup>
import { Sapling } from "@saplingai/sapling-js/observer";
import { ref, onMounted } from 'vue'

const editorRef = ref(null);

onMounted(() => {
  Sapling.init({
    key: '<YOUR_API_KEY>',
    endpointHostname: 'https://api.sapling.ai',
    editPathname: '/api/v1/edits',
    statusBadge: true,
    mode: 'dev',
  });

  Sapling.observe(editorRef.value);
})
</script>

<template>
  <div id="editor" ref="editorRef" sapling-ignore="true" contenteditable>
    Lets get started.
  </div>
</template>

<style scoped>
#editor{
  height: 200px;
  width:  400px;
  padding: 10px;
  margin: 10px;
  border: 1px solid;
}
</style>

// javascript/react-app/src/App.jsx
import { useEffect } from 'react';
import { Sapling } from "@saplingai/sapling-js/observer";


function App() {
  useEffect(() => {
    Sapling.init({
      key: '<YOUR_API_KEY>',
      endpointHostname: 'https://api.sapling.ai',
      editPathname: '/api/v1/edits',
      statusBadge: true,
      mode: 'dev',
    });

    const editor = document.getElementById('editor');
    Sapling.observe(editor);
  }, []);

  return (
    <div id="editor" sapling-ignore="true" contentEditable="true">
      Lets get started!
    </div>
  );
}

export default App;
